### PR TITLE
sharedstuff.org

### PR DESCRIPTION
**Pull request by jancborchardt**
Got a proper domain, the A record on the registrar is already added, merging this in should activate it.

### CODE REVIEW

**Comment by shared-stuff** [comment]
Wow, own domain. That was fast. I'm impressed. Thank you for the registration.

But it seems not to work, Do I have to be a paying github customer to
use this? O do I have to configure something somewhere?

On Tue, May 29, 2012 at 5:40 PM, Jan-Christoph Borchardt
reply@reply.github.com
wrote:

**Comment by shared-stuff** [comment]
Ups, now everything looks broken. Can you fix it?

**Comment by jancborchardt** [comment]
Yeah, I’m on it, will check with the A records at Gandi.

**Comment by jancborchardt** [comment]
I did everything as described on the [Github pages help](http://help.github.com/pages/#custom_domains). Added A records for \* and www pointing to 204.232.175.78

It will work in a few hours I think, once the DNS info has propagated. Until then, http://shared-stuff.github.com will work as intended. Or what do you mean with »everything looks broken«? (And no, you don’t need to be a paying Github customer for this to work.)

**Comment by jancborchardt** [comment]
Ok, damn, the .github.com does not seem to work after all. Let’s do it like that: you remove the CNAME from the repo again. And I will deploy it on 5apps, and point the domain name to that.

**Comment by shared-stuff** [comment]
OK, I removed the CNAME, but it seems it will also need time until
this change is reverted.

On Tue, May 29, 2012 at 10:09 PM, Jan-Christoph Borchardt
reply@reply.github.com
wrote:

**Comment by shared-stuff** [comment]
Wouldn't it make more sense to deploy it to a different github page in
order to test the  www.sharedstuff.org <-> github connection? I mean,
nobody knows www.sharedstuff.org yet. So it's not important that
www.sharedstuff.org works now but to make it work with
http://shared-stuff.github.com soon.

Testing it with a different github account could bring some insights.

On Tue, May 29, 2012 at 10:09 PM, Jan-Christoph Borchardt
reply@reply.github.com
wrote:

**Comment by jancborchardt** [comment]
Yes, sorry for the breakage again. I deployed it on 5apps at https://5apps.com/apps/4fc52ef3c439346eb40000f5 and added you as collaborator. This is a separate instance not linked to Github but it has the same code as in this repo.

This is also where the now working http://sharedstuff.org is A record directed to. I think it’s good to have sharedstuff.org as official domain and shared-stuff.github.com as experimental dev playground, what do you think?

**Comment by shared-stuff** [comment]
> I think it’s good to have sharedstuff.org as official domain and shared-stuff.github.com
> as experimental dev playground, what do you think?

Agreed, Good Idea!
I hope 5apps.com is reliable and fast.

**Comment by shared-stuff** [comment]
At least on my computers http://www.sharedstuff.org does not work but
http://sharedstuff.org do work.

One remaining problem with this hosting is, that the files are not
gzip'ed . Normally every webhoster provides gziping as it halves the
data to transfer.

Does 5apps has no gziping or must is be enabled somehow? (Its enabled
for github pages by default).

**Comment by jancborchardt** [comment]
@shared-stuff @shybyte by the way, I got mail from Gandi about domain expiry and thought it’s probably best to transfer the domain to you anyway. Then you can manage everything directly. Can you check what info you need for your provider?

You probably solved the question above already, but I think yes, 5apps does gzipping. @skddc @galfert? They also minify the code, and automatically generate an AppCache manifest so all the files don’t have to be loaded every time.

**Comment by shybyte** [comment]
@jancborchardt  I'm not so experienced with this domain stuff (embarrassing , I know). What exactly do I have to do for the domain transfer? Or where can I read what I have to do? What do you mean with "my provider"?

**Comment by jancborchardt** [comment]
@shybyte if you don’t have a domain yet, you probably don’t have a provider/registrar yet either. That’s the service which handles the domain for you, and lots of them also offer hosting (which isn’t needed in this case because of Github Pages / 5apps). For just a domain (com/net/org), it’s usually only ~12 € a year. Personally I use [Gandi](http://gandi.net) and fully recommend them. If you get an account there, you can [request a transfer](https://www.gandi.net/domain/transfer). Then I need to confirm the transfer and that should be it. :)

**Comment by shybyte** [comment]
@jancborchardt  I registered at Gandi, but when I try to request a domain transfer I get: 

Error:
This domain name (sharedstuff.org) is already at Gandi, but under a different handle. If you are the owner and want    to change the owner handle to yourself, see our [wiki](http://wiki.gandi.net/en/contacts/changeowner)

For me it seems, that the domain owner needs to request the transfer. (?)

**Pull request merged**
